version: '3.5'

services:

  socker:
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - /private/var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development